model:
  name: cb
  hyperparams:
    depth: 6
    n_estimators: 1000
    eval_metric: R2
    task_type: CPU
    random_seed: 0
    learning_rate: 0.3
    l2_leaf_reg: 3
    loss_function: RMSE
    metric_period: 10
    logging_level: Verbose

training:
  checkpoint_name: cb_model.p

inference:
  checkpoint_name: cb_model.p

logging:
  commit_id: None # Adding new fields from a script is prohibited by default
  mlflow:
    exp_name: MLOps hw2
    tracking_uri: http://127.0.0.1:5000
