model:
  name: rf
  hyperparams:
    n_estimators: 100
    random_state: 0
    verbose: 0
    n_jobs: -1

training:
  checkpoint_name: rf_model.p

inference:
  checkpoint_name: rf_model.p

logging:
  commit_id: None # Adding new fields from a script is prohibited by default
  mlflow:
    exp_name: MLOps hw2
    tracking_uri: http://127.0.0.1:5000
