name: pre_commit_hooks_workflow
run-name: Run pre-commit hooks after push by ${{ github.actor }}
on: [push]
jobs:
  run-pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files
